networks:
  t3_proxy:
    external: true

services:
  bentopdf:
    image: bentopdf/bentopdf:latest
    container_name: bentopdf
    networks:
      - t3_proxy
    #    ports:
    #      - '3000:8080'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
          pids: 1
        reservations:
#          cpus: '0.25'
          memory: 5M